services:
  - type: web
    name: skin-diseases-detection
    runtime: python
    rootDir: .
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app --config gunicorn.conf.py
    envVars:
      - key: PYTHON_VERSION
        value: "3.11"
      - key: TF_CPP_MIN_LOG_LEVEL
        value: "3"
      - key: TF_ENABLE_ONEDNN_OPTS
        value: "0"
      - key: HF_REPO_ID
        value: ""
      - key: HF_TOKEN
        value: ""