services:
  - type: web
    name: skin-diseases-detection
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app --config gunicorn.conf.py
    envVars:
      - key: PYTHON_VERSION
        value: "3.10.0"
      - key: HF_REPO_ID
        value: ""   # ← set your Hugging Face repo ID here
      - key: HF_TOKEN
        value: ""   # ← set your HF token here (if private repo)